Repository prezly/javascript-sdk, pull requests merged in 2021-04, with the labels that each got.

#26 [DEV-2437] Fix - Undocumented API properties
  src/types/Coverage.ts
  src/types/Newsroom.ts
Labels: bug, enhancement

#27 [DEV-2425] Fix - Story content type
  src/types/Story.ts
Labels: bug, documentation

#30 [DEV-2511] Feature - Newsroom Languages API
  src/Sdk/NewsroomLanguages/NewsroomLanguages.ts
  src/Sdk/NewsroomLanguages/index.ts
  src/Sdk/NewsroomLanguages/types.ts
  src/Sdk/Sdk.ts
  src/Sdk/index.ts
  src/Sdk/routing.ts
  src/index.ts
  src/types/NewsroomCompanyInformation.ts
  src/types/NewsroomLanguageSettings.ts
  src/types/index.ts
Labels: enhancement

#31 [DEV-2438] Feature - Newsroom Languages API (part 2)
  src/Sdk/NewsroomLanguages/NewsroomLanguages.ts
  src/Sdk/NewsroomLanguages/lib.ts
  src/Sdk/NewsroomLanguages/types.ts
Labels: enhancement

#32 [DEV-2559] Feature - Newsroom Webhooks API
  src/Sdk/NewsroomWebhooks/NewsroomWebhooks.ts
  src/Sdk/NewsroomWebhooks/index.ts
  src/Sdk/NewsroomWebhooks/types.ts
  src/Sdk/Sdk.ts
  src/Sdk/routing.ts
  src/types/NewsroomWebhook.ts
  src/types/WebhookEvent.ts
  src/types/index.ts
Labels: enhancement

#33 [DEV-2646] Feature - Stories SDK include sparse fields
  README.md
  src/Sdk/Stories/Stories.ts
  src/Sdk/Stories/types.ts
  src/index.ts
  src/types/Story.ts
  src/types/index.ts
Labels: enhancement
