Repository prezly/javascript-sdk, pull requests merged in 2021-11, with the labels that each got.

#84 Expose EmailBranding and EmailBrandingMode types
  src/index.ts
Labels: enhancement

#85 [DEV-3797] Document Story Update API v2
  src/Sdk/Stories/Stories.ts
  src/Sdk/Stories/index.ts
  src/Sdk/Stories/types.ts
  src/Sdk/index.ts
  src/index.ts
Labels: enhancement

#86 [DEV-3803] Document Campaign Recipients API
  src/Sdk/CampaignRecipients/CampaignRecipients.ts
  src/Sdk/CampaignRecipients/index.ts
  src/Sdk/CampaignRecipients/types.ts
  src/Sdk/Sdk.ts
  src/Sdk/index.ts
  src/Sdk/routing.ts
  src/types/EmailRecipient.ts
  src/types/index.ts
  src/types/scopes/AllContactsScope.ts
  src/types/scopes/CampaignRecipientsScope.ts
  src/types/scopes/CampaignReportScope.ts
  src/types/scopes/ContactEmployeesScope.ts
  src/types/scopes/ContactOrganisationsScope.ts
  src/types/scopes/ContactsScope.ts
  src/types/scopes/index.ts
Labels: enhancement

#87 Refactor - Avoid default exports
  package.json
  src/Sdk/Coverage/types.ts
  src/Sdk/NewsroomWebhooks/types.ts
  src/Sdk/Sdk.ts
  src/Sdk/Subscriptions/types.ts
  src/Sdk/index.ts
  src/Sdk/types.ts
  src/index.ts
  src/types/Campaign.ts
  src/types/Category.ts
  src/types/Contact.ts
  src/types/ContactDuplicateSuggestion.ts
  src/types/ContactRef.ts
  src/types/CountryRef.ts
  src/types/Coverage.ts
  src/types/CoverageProvider.ts
  src/types/CoverageType.ts
  src/types/CultureRef.ts
  src/types/DnsConfigurationInstruction.ts
  src/types/EmailBranding.ts
  src/types/EmailBrandingMode.ts
  src/types/EmailRecipient.ts
  src/types/EmailSubscription.ts
  src/types/Entity.ts
  src/types/JobState.ts
  src/types/Newsroom.ts
  src/types/NewsroomCompanyInformation.ts
  src/types/NewsroomContact.ts
  src/types/NewsroomDomain.ts
  src/types/NewsroomDomainShareInstructions.ts
  src/types/NewsroomLanguageSettings.ts
  src/types/NewsroomThemePreset.ts
  src/types/NewsroomWebhook.ts
  src/types/SenderAddress.ts
  src/types/SenderDomain.ts
  src/types/Story.ts
  src/types/ThemeFeature.ts
  src/types/UnsubscribeReason.ts
  src/types/UserRef.ts
  src/types/Utm.ts
  src/types/WebhookEvent.ts
  src/types/common/OEmbedInfo.ts
  src/types/common/Pagination.ts
  src/types/common/Query.ts
  src/types/common/UploadcareFile.ts
  src/types/common/UploadcareImage.ts
  src/types/common/Utm.ts
  src/types/common/Warning.ts
  src/types/common/index.ts
  src/types/index.ts
  src/types/scopes/AllContactsScope.ts
  src/types/scopes/CampaignRecipientsScope.ts
  src/types/scopes/CampaignReportScope.ts
  src/types/scopes/ContactEmployeesScope.ts
  src/types/scopes/ContactOrganisationsScope.ts
  tsconfig.json
Labels: refactoring

#83 Deprecate email_branding.link_hover_color
  src/types/EmailBranding.ts
Labels: refactoring

#88 Feature - Support Newsroom Galleries API
  src/Sdk/NewsroomGalleries/NewsroomGalleries.ts
  src/Sdk/NewsroomGalleries/index.ts
  src/Sdk/Sdk.ts
  src/Sdk/routing.ts
  src/types/GalleryStatus.ts
  src/types/NewsroomGallery.ts
  src/types/NewsroomGalleryImage.ts
  src/types/index.ts
Labels: enhancement

#89 Add email_branding property to NewsroomThemePreset
  src/types/NewsroomThemePreset.ts
Labels: enhancement

#90 Add galleries pagination and filters support
  src/Sdk/NewsroomGalleries/NewsroomGalleries.ts
  src/Sdk/NewsroomGalleries/types.ts
  src/types/Newsroom.ts
Labels: enhancement

#92 Stringify scope and query when doing galleries list request
  src/Sdk/NewsroomGalleries/NewsroomGalleries.ts
Labels: bug

#91 Specify all features in ThemeFeature enum
  src/types/ThemeFeature.ts
Labels: enhancement

#94 Refactor - Remove `@prezly/slate-types` dependency
  package-lock.json
  package.json
  src/Sdk/NewsroomContacts/types.ts
  src/Sdk/NewsroomSubscriptions/types.ts
  src/Sdk/Subscriptions/types.ts
  src/index.ts
  src/types/Contact.ts
  src/types/Coverage.ts
  src/types/Newsroom.ts
  src/types/NewsroomContact.ts
  src/types/NewsroomGalleryImage.ts
  src/types/NewsroomThemePreset.ts
  src/types/common/UploadcareFile.ts
  src/types/common/UploadcareImage.ts
  src/types/common/index.ts
Labels: refactoring

#95 Support custom privacy policy link in Newsrooms API
  src/Sdk/Newsrooms/types.ts
  src/types/Newsroom.ts
Labels: enhancement

#96 Fix - Missing Utm interface properties
  src/Sdk/Subscriptions/types.ts
  src/types/common/Utm.ts
  src/types/common/index.ts
Labels: enhancement

#97 Feature - Support newsroom tracking settings
  src/types/Newsroom.ts
  src/types/TrackingPolicy.ts
  src/types/index.ts
Labels: enhancement
