Repository prezly/javascript-sdk, pull requests merged in 2021-06, with the labels that each got.

#44 [DEV-3266] Fix NewsroomContact update method
  src/Sdk/NewsroomContacts/NewsroomContacts.ts
Labels: bug

#45 Fix - Outdated interfaces
  src/types/Newsroom.ts
  src/types/UserRef.ts
Labels: bug, enhancement

#46 Fix - UserRef interface
  src/index.ts
  src/types/Story.ts
  src/types/UserAccountRef.ts
  src/types/UserRef.ts
  src/types/index.ts
Labels: bug, enhancement

#52 Update Newsroom API interfaces
  src/Sdk/Newsrooms/types.ts
  src/types/Newsroom.ts
Labels: enhancement
