Repository prezly/javascript-sdk, pull requests merged in 2022-10, with the labels that each got.

#145 Define additional gallery API entity properties
  src/types/NewsroomGallery.ts
Labels: enhancement

#146 Implement galleries order SDK
  src/Sdk/NewsroomGalleries/NewsroomGalleries.ts
  src/Sdk/NewsroomGalleries/types.ts
Labels: enhancement

#152 Drop `is_license_contact` and `is_locked` from Contact type
  src/types/Contact.ts
Labels: refactoring

#153 Refactor - Drop inexisting properties
  src/types/Campaign.ts
  src/types/Contact.ts
  src/types/scopes/CampaignReportScope.ts
Labels: refactoring

#154 Support attached_gallery_content property
  src/Sdk/Stories/types.ts
  src/types/Story.ts
Labels: enhancement

#155 [DEV-9064] Refactor - Entity sub-types namespaces
  src/endpoints/Coverage/types.ts
  src/endpoints/NewsroomDomains/Client.ts
  src/endpoints/NewsroomGalleries/types.ts
  src/endpoints/NewsroomPrivacyRequests/types.ts
  src/endpoints/NewsroomWebhooks/types.ts
  src/endpoints/Newsrooms/types.ts
  src/endpoints/Stories/Client.ts
  src/endpoints/Stories/types.ts
  src/endpoints/Subscriptions/Client.ts
  src/endpoints/Subscriptions/types.ts
  src/types/Campaign.ts
  src/types/Category.ts
  src/types/Contact.ts
  src/types/ContactDuplicateSuggestion.ts
  src/types/ContactRef.ts
  src/types/Country.ts
  src/types/CoverageEntry.ts
  src/types/Culture.ts
  src/types/CultureRef.ts
  src/types/EmailBranding.ts
  src/types/EmailBrandingMode.ts
  src/types/EmailRecipient.ts
  src/types/GalleryStatus.ts
  src/types/License.ts
  src/types/LicenseStatus.ts
  src/types/Newsroom.ts
  src/types/NewsroomContact.ts
  src/types/NewsroomDomain.ts
  src/types/NewsroomDomainShareInstructions.ts
  src/types/NewsroomGallery.ts
  src/types/NewsroomGalleryImage.ts
  src/types/NewsroomLanguageSettings.ts
  src/types/NewsroomTheme.ts
  src/types/NewsroomThemePreset.ts
  src/types/NewsroomWebhook.ts
  src/types/PrivacyRequest.ts
  src/types/SenderAddress.ts
  src/types/SenderDomain.ts
  src/types/Snippet.ts
  src/types/Story.ts
  src/types/ThemeFeature.ts
  src/types/ThemeStatus.ts
  src/types/TrackingPolicy.ts
  src/types/User.ts
  src/types/common/Notification.ts
  src/types/index.ts
Labels: refactoring

#161 Feature - Migrate more types from the app
  src/endpoints/CampaignRecipients/scopes.ts
  src/types/Campaign.ts
  src/types/Category.ts
  src/types/Contact.ts
  src/types/Country.ts
  src/types/CoverageEntry.ts
  src/types/Culture.ts
  src/types/Currency.ts
  src/types/EmailRecipient.ts
  src/types/Entity.ts
  src/types/License.ts
  src/types/NewsroomDomain.ts
  src/types/NewsroomTheme.ts
  src/types/Plan.ts
  src/types/SenderAddress.ts
  src/types/SenderDomain.ts
  src/types/Story.ts
  src/types/User.ts
  src/types/UserAccount.ts
  src/types/index.ts
Labels: enhancement, refactoring
